repos:
  - repo: https://github.com/MarketSquare/robotframework-tidy
    rev: 4.1.0
    hooks:
      - id: robotidy
        verbose: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace